### ISSUE TITLE
Docker setup: "-A:build (No such file or directory)"

### ISSUE THREAD

**Issue by vbhayden** [yetanalytics/datasim#28]
Morning team,

For the Docker deployment commands, the first command use the Makefile to generate the `target` contents, which will then be pulled into the image by the Dockerfile.  When I run that first command:
```
make clean bundle
```

it snags on `-A:build (No such file or directory)`.  Is there maybe another step involved that might've been excluded from the Makefile?  

Thanks

**Comment by cliffcaseyyet** [comment]
Hi Trey,

I updated the CLI section in docs to more accurately reflect the easiest current run procedures. We are formalizing the docker parts after some rework so we'll update you when that's in a better place.

Thanks,
-Cliff

**Comment by jgedne** [comment]
I am having this same issue trying to build without docker on a clean install  
this is the output: 

----------- 
datasim@ip-172-31-5-142:~/Documents/datasim$ make bundle
mkdir -p target/bundle
rm -f pom.xml
clojure -X:depstar uberjar :no-pom false :sync-pom true :aliases '[:cli]' :aot true :group-id com.yetanalytics :artifact-id datasim-cli :version '"0.1.0-SNAPSHOT"' :jar target/bundle/datasim_cli.jar :main-class com.yetanalytics.datasim.main
Exception in thread "main" java.io.FileNotFoundException: -X:depstar (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at clojure.lang.Compiler.loadFile(Compiler.java:7449)
        at clojure.main$load_script.invokeStatic(main.clj:278)
        at clojure.main$script_opt.invokeStatic(main.clj:338)
        at clojure.main$script_opt.invoke(main.clj:333)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
Makefile:12: recipe for target 'target/bundle/datasim_cli.jar' failed
make: *** [target/bundle/datasim_cli.jar] Error 1
--------------

**Comment by milt** [comment]
We recently started publishing docker builds on this, so there now isn't a need to manually build in most cases https://github.com/yetanalytics/datasim/pull/73

Addressing @jgedne's issue specifically, it looks like you may need to upgrade your clojure CLI to a version >= 1.10.1.679, when [execution mode](https://clojure.org/reference/deps_and_cli#_execute_a_function) was added.

See https://clojure.org/releases/tools#v1.10.1.697 in the changelog
